# 1. Libraries----
suppressPackageStartupMessages(library(survival))
suppressPackageStartupMessages(library(SurvMetrics))
#library(caret)
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(pec))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(mice))
suppressPackageStartupMessages(library(measures))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(survminer))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(faux))
suppressPackageStartupMessages(library(EnvStats))